### ISSUE TITLE
Problems encountered in Creating Submission Files

### ISSUE THREAD

**Issue by txy8496** [cybercore-co-ltd/Track4_aicity_2022#1]
Dear Team,

I have some problems when I try to create submission files according to the manual. 

When I tried to execute the code below (I have used the pretrained model downloaded from the link and finished running the detector and ensembling results)
_./tools/create_submission_file.sh <path/to/videos>_
 I found an OS error which said as follows.

_OSError: ./data/Auto-retail-syndata-release/anns/val.txt not found._

I cannot find the folder **anns**, seems there does not contain **anns** folder in the original data (i.e. Auto-retail-syndata-release) published by the organizers. Then how can I resolve this problem to create the submission files?

I appreciate if you would like to help me resolve it out.
Thank you for your help.

Best,
Xinyu

**Comment by thuyngch** [comment]
Hi @txy8496 ,

I updated the readme in the section https://github.com/cybercore-co-ltd/Track4_aicity_2022#dataset-preparation-and-environment-setup
I added a link to download the file that you need to run.
Please check it, thanks!
